### ISSUE TITLE
fadein and fadeout

### ISSUE THREAD

**Issue by vinnitu** [samirkumardas/pcm-player#4]
Hello!

Can you explain for what do you fadein and fadeout?

https://github.com/samirkumardas/pcm-player/blob/d4bd3bbbf0f83312d33ddd72624d2680549ece09/pcm-player.js#L105

**Comment by samirkumardas** [comment]
The purpose of fading/fadeout is to soothe the click noise.  You can check this post to get an idea about the reason of the click noise http://alemangui.github.io/blog//2015/12/26/ramp-to-value.html

**Comment by vinnitu** [comment]
ok, but why you don't use solution from article?

**Comment by samirkumardas** [comment]
Because I don't want to stop playing, that solution is not appropriate in this case. I gave that article link to know what the click noise is and what the reason behind that. 

As this player is intended to play PCM streaming, there is a possibility of getting the incorrectly cut signal that causes the click noise.

**Comment by nickrobillard** [comment]
@samirkumardas I just wanted to mention that I ended up removing the fade in/fade out code. For me, it was _causing_ the click noise between segments. I'm using Chrome/85.0.4183.121. Would you be open to making fade in/fade out an option so that the user can choose whether to use that feature?
